/**
 * Copyright 2013-2022 iSignal Research Labs Pvt Ltd.
 *
 * This file is part of isrRAN.
 *
 * isrRAN is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of
 * the License, or (at your option) any later version.
 *
 * isrRAN is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * A copy of the GNU Affero General Public License can be found in
 * the LICENSE file in the top-level directory of this distribution
 * and at http://www.gnu.org/licenses/.
 *
 */

#ifndef ISRRAN_PBCH_MSG_NR_H
#define ISRRAN_PBCH_MSG_NR_H

#include "isrran/config.h"
#include "isrran/phy/common/phy_common_nr.h"
#include <stdbool.h>
#include <stdint.h>

/**
 * @brief NR PBCH payload size generated by higher layers, deduced from TS 38.331 MIB description
 */
#define ISRRAN_PBCH_MSG_NR_SZ 24

/**
 * @brief Define the payload buffer for ISRRAN_PBCH_MSG_NR_SZ to be 32 for alignment purposes
 */
#define ISRRAN_PBCH_MSG_NR_MAX_SZ 32

/**
 * @brief Describes the NR PBCH message
 */
typedef struct ISRRAN_API {
  uint8_t payload[ISRRAN_PBCH_MSG_NR_MAX_SZ]; ///< Actual PBCH payload provided by higher layers
  uint8_t sfn_4lsb;                       ///< SFN 4 LSB
  uint8_t ssb_idx;                        ///< SS/PBCH blocks index described in TS 38.213 4.1
  uint8_t k_ssb_msb;                      ///< Subcarrier offset MSB described in TS 38.211 7.4.3.1
  bool    hrf;                            ///< Half Radio Frame bit
  bool    crc;                            ///< Decoder only, it is true only if the received CRC matches
} isrran_pbch_msg_nr_t;

typedef struct ISRRAN_API {
  uint32_t                    sfn;                    ///< System frame number
  uint8_t                     ssb_idx;                ///< SS/PBCH blocks index described in TS 38.213 4.1
  bool                        hrf;                    ///< Half Radio Frame bit
  isrran_subcarrier_spacing_t scs_common;             ///< Subcarrier spacing common
  uint32_t                    ssb_offset;             ///< SSB subcarrier offset
  isrran_dmrs_sch_typeA_pos_t dmrs_typeA_pos;         ///< DMRS typeA position
  uint32_t                    coreset0_idx;           ///< CORESET Zero configuration index (0-15)
  uint32_t                    ss0_idx;                ///< SearchSpace Zero configuration index (0-15)
  bool                        cell_barred;            ///< Set to true if the cell is barred
  bool                        intra_freq_reselection; ///< Set to true if allowed
  uint32_t                    spare;                  ///< Unused bits
} isrran_mib_nr_t;

ISRRAN_API bool isrran_pbch_msg_nr_is_mib(const isrran_pbch_msg_nr_t* msg);

ISRRAN_API int isrran_pbch_msg_nr_mib_pack(const isrran_mib_nr_t* mib, isrran_pbch_msg_nr_t* msg);

ISRRAN_API int isrran_pbch_msg_nr_mib_unpack(const isrran_pbch_msg_nr_t* pbch_msg, isrran_mib_nr_t* mib);

ISRRAN_API uint32_t isrran_pbch_msg_info(const isrran_pbch_msg_nr_t* msg, char* str, uint32_t str_len);

ISRRAN_API uint32_t isrran_pbch_msg_nr_mib_info(const isrran_mib_nr_t* mib, char* str, uint32_t str_len);

#endif // ISRRAN_PBCH_MSG_NR_H
